---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(INLA)
library(lubridate)

source("../src/prep-fit-data.R")
source("../src/model-formulas.R")
source("../src/fit-inla-model.R")
source("../src/sample-forecasts.R")
source("../src/retrospective.R")

inla.setOption(inla.mode="classic")

```

```{r}
forecast_dates <- c("2023-09-16", "2023-10-28")

forecast_dates <- ymd(forecast_dates)
```

```{r}
################ choose disease and dates for datasets #############

test <- read_data_model("rsv_2021")

###### dates
#forecast_dates <- filter_by_epiweek(test, 37, 20, "2023-09-20") #Note that dates produced will be the first forecast date (horizon 1- with NA starting at that date) and the reference date will be the week before  

#################### Produce actual Forecast ####################
forecast_dates |> 
  map(generate_save_weekly_forecast_besag_rsv, 
      disease_df = test, 
      folder_name = "test_2021_rsv_besag") ##//// THIS CREATES A FOLDER


#produce forecasts for all epiweeks over a season and save to folder 

#generate_save_weekly_forecast = exchangeable (graph off)- works for covid and flu 
#generate_save_weekly_forecast_besag = besag proper (graph on)- works for covid and flu

#generate_save_weekly_forecast_rsv = exchangeable (graph off)- works for rsv 
#generate_save_weekly_forecast_besag_rsv = besag proper (graph on)- works for rsv


```

#baseline

```{r}
library(readr)
library(dplyr)
library(tidyr)
library(purrr)
library(checkmate)
library(cli)
library(epidatr)
library(epiprocess)
library(epipredict)
library(ggplot2)
library(plotly)
```

```{r}
############### Prep dataframes/dates ########################
test2 <- adjust_data(test)
baseline_dates <- ymd(forecast_dates) - 7

############### Prep data ########################
target_edf <- prepare_epi_data(test2)  

############## Generate forecasts for each date in the list ###################
forecasts_list <- lapply(baseline_dates, generate_forecasts_for_date, target_edf=target_edf)
```

```{r}
####################### format #####################################
output_dirpath <- "../processed_data/test_flu_Baseline_2021" # Define your output directory path
for(i in seq_along(forecasts_list)) {
  format_and_save_forecasts(forecasts_list[[i]], baseline_dates[i], output_dirpath)
}
```




